A_STORE_NAME = "Store Name"
A_STORE_ADDRESS = "502 North Street"

ANOTHER_STORE_NAME = "Store Number 2"
ANOTHER_STORE_ADDRESS = "600 Dear Av"

A_STORE_ID = 1

AN_ARTICLE_NAME = "Running Shoes"
AN_ARTICLE_DESCRIPTION = "Confortable, great feeling"
AN_ARTICLE_PRICE = 200
AN_ARTICLE_TOTAL_IN_SHELF = 5
AN_ARTICLE_TOTAL_IN_VAULT = 10

ANOTHER_ARTICLE_NAME = "Classic Shoes"
ANOTHER_ARTICLE_DESCRIPTION = "Elegant, great style"
ANOTHER_ARTICLE_PRICE = 400
ANOTHER_ARTICLE_TOTAL_IN_SHELF = 3
ANOTHER_ARTICLE_TOTAL_IN_VAULT = 5

