development:
  adapter: postgresql
  encoding: utf8
  reconnect: false
  host: localhost
  database: super_zapato_dev
  pool: 5

test:
  adapter: postgresql
  encoding: utf8
  reconnect: false
  host: localhost
  database: super_zapato_test
  pool: 5

production:
  adapter: postgresql
  encoding: utf8
  reconnect: false
  host: localhost
  database: super_zapato_prod
  pool: 5

