AN_ARTICLE_PARAMS = {
  name: AN_ARTICLE_NAME,
  description: AN_ARTICLE_DESCRIPTION,
  price: AN_ARTICLE_PRICE,
  total_in_shelf: AN_ARTICLE_TOTAL_IN_SHELF,
  total_in_vault: AN_ARTICLE_TOTAL_IN_VAULT
}

ANOTHER_ARTICLE_PARAMS = {
  name: ANOTHER_ARTICLE_NAME,
  description: ANOTHER_ARTICLE_DESCRIPTION,
  price: ANOTHER_ARTICLE_PRICE,
  total_in_shelf: ANOTHER_ARTICLE_TOTAL_IN_SHELF,
  total_in_vault: ANOTHER_ARTICLE_TOTAL_IN_VAULT
}

